### ISSUE TITLE
Doesn't work on Ubuntu 16.04

### ISSUE THREAD

**Issue by jedrekdomanski** [josefbehr/somafm-qt#4]
When icon is added to the system dock it won't launch. It only works when launched from terminal using the command `/snap/bin/somafm-qt`

**Comment by josefbehr** [comment]
@jedrekdomanski Thanks for the report. I´m not sure I understand the problem completely. Can you specify a bit more, what exactly happens and what you´d expect to happen?

**Comment by jedrekdomanski** [comment]
I installed the app, launched it and it worked fine. Then, I added the icon to the left pane (dock), closed the app, clicked the icon in the dock and it does't work. It works only if I run the app from the terminal `/snap/bin/somafm-qt`, it doesn't work if I run it from the dash or dock. Does it make sense?

**Comment by josefbehr** [comment]
@jedrekdomanski yes! Thanks a lot.

@fredix Any idea if this is a problem with the snap support or wrapper you added? Otherwise I´ll try to reproduce and fix.

**Comment by jedrekdomanski** [comment]
This is not just the snap app. I tried the app from ubuntu software center before and it was the same.
![image](https://user-images.githubusercontent.com/5911945/97869307-8a7c8d00-1d11-11eb-999f-e1eb103c7fa7.png)
