### ISSUE TITLE
Closing application window will quit the app if tray icon is enabled instead of just closing the window

### ISSUE THREAD

**Issue by pbek** [josefbehr/somafm-qt#6]
If you click on the "X" to close the application window the app will quit even if the tray icon is enabled, instead of just closing the window.

**Comment by pbek** [comment]
I'd "fix" that by allowing the window to be hidden on "close" and by introducing a tray menu with a "Quit" menu entry later today.

**Comment by pbek** [comment]
Would be solved by https://github.com/josefbehr/somafm-qt/pull/7

**Comment by josefbehr** [comment]
Thank you!
